### ISSUE TITLE
Can't build generated code

### ISSUE THREAD

**Issue by FirowMD** [raysan5/rguilayout#9]
I've downloaded raylib-4.5.0, raygui-3.5.0.
Command which I use to build generated code is:
`gcc layout_name.c -lraylib -lGL -lm -lpthread -ldl -lrt -lX11`

Output:
```
layout_name.c: In function ‘main’:
layout_name.c:72:21: warning: implicit declaration of function ‘GuiTextBoxMulti’; did you mean ‘GuiTextBox’? [-Wimplicit-function-declaration]
   72 |                 if (GuiTextBoxMulti((Rectangle){ 384, 240, 624, 312 }, TextmultiBox003Text, 128, TextmultiBox003EditMode)) TextmultiBox003EditMode = !TextmultiBox003EditMode;
      |                     ^~~~~~~~~~~~~~~
      |                     GuiTextBox
/usr/bin/ld: /tmp/ccUI6gRB.o: in function `main':
layout_name.c:(.text+0xeb31): undefined reference to `GuiTextBoxMulti'
collect2: error: ld returned 1 exit status
```

**Comment by raysan5** [comment]
@FirowMD I'm afraid latest rGuiLayout requires latest `raygui 4.0-dev` from github master branch.

**Comment by FirowMD** [comment]
@raysan5 Even with master branch. Waiting for a new version..
P.S. Hello window `Welcome to rGuiLayout!` shows version 3.0 (Oct. 2022), when it should show 3.1. Because I've downloaded 3.1 (both Linux and Windows version)

**Comment by FirowMD** [comment]
@raysan5 I don't know how to do it. There is a `makefile`, but raw `make` doesn't do things

**Comment by FirowMD** [comment]
I've built windows version of `rguilayout`, which is 4.0. Result is same:
```
layout_name.c: In function ‘main’:
layout_name.c:68:17: error: ‘WindowBox000Active’ undeclared (first use in this function); did you mean ‘windowActive’?
   68 |             if (WindowBox000Active)
      |                 ^~~~~~~~~~~~~~~~~~
      |                 windowActive
layout_name.c:68:17: note: each undeclared identifier is reported only once for each function it appears in
layout_name.c:71:21: warning: implicit declaration of function ‘GuiTextBoxMulti’; did you mean ‘GuiTextBox’? [-Wimplicit-function-declaration]
   71 |                 if (GuiTextBoxMulti((Rectangle){ 432, 216, 528, 384 }, TextmultiBox003Text, 128, TextmultiBox003EditMode)) TextmultiBox003EditMode = !TextmultiBox003EditMode;
      |                     ^~~~~~~~~~~~~~~
      |                     GuiTextBox
```

**Comment by FirowMD** [comment]
VS2022 shows this error too:
```
1>layout_name.c
1>C:\Users\geork\Desktop\rproj\raygui.h(2320,113): warning C4018: '<': signed/unsigned mismatch
1>C:\Users\geork\Desktop\rproj\raygui.h(2323,62): warning C4018: '>': signed/unsigned mismatch
1>C:\Users\geork\Desktop\rproj\raygui.h(2358,56): warning C4018: '<': signed/unsigned mismatch
1>C:\Users\geork\Desktop\rproj\raygui.h(2378,78): warning C4018: '<': signed/unsigned mismatch
1>C:\Users\geork\Desktop\rproj\raygui.h(2403,44): warning C4018: '>=': signed/unsigned mismatch
1>C:\Users\geork\Desktop\rproj\layout_name.c(64,35): error C2065: 'WindowBox000Active': undeclared identifier
1>C:\Users\geork\Desktop\rproj\layout_name.c(66,36): error C2065: 'WindowBox000Active': undeclared identifier
1>C:\Users\geork\Desktop\rproj\layout_name.c(67,21): warning C4013: 'GuiTextBoxMulti' undefined; assuming extern returning int
```

**Comment by raysan5** [comment]
I see. `GuiTextBoxMulti()` was removed and `WindowBox000Active` was renamed recently. I will review it for next release.

**Comment by raysan5** [comment]
Working on aligning `rGuiLayout 4.0` with `raygui 4.0`.
